/**
 * Model Schema
 * 
 * A model represents a person avatar with physical description,
 * identity references, and optional emotion/pose presets.
 * Models are stored on disk in individual folders with manifest.json and image files.
 */

/**
 * @typedef {Object} Model
 * @property {string} id - Unique identifier (e.g., "model_20260105_abc123")
 * @property {string} name - Display name (e.g., "Elegant Brunette")
 * @property {string} label - Short description for UI
 * @property {string} promptSnippet - Detailed physical description for prompts
 * @property {number|null} heightCm - Height in centimeters
 * @property {string} bodyType - Body type description (slim, athletic, curvy, etc.)
 * @property {string} faceExpressions - Characteristic face expressions
 * @property {string} poses - Typical poses and movement style
 * @property {string} background - Professional background/characteristics (e.g., fashion, extreme)
 * @property {string} previewSrc - Path to preview image (relative to models folder)
 * @property {string} dirPath - Path to model folder (relative to store/models/)
 * @property {Array<string>} imageFiles - List of image filenames in the folder
 * @property {string} createdAt - ISO timestamp
 * @property {string} updatedAt - ISO timestamp
 */

export const BODY_TYPES = [
  'slim', 'athletic', 'curvy', 'petite', 'tall', 'average', 'plus-size'
];

export function generateModelId() {
  const now = new Date();
  const datePart = now.toISOString().slice(0, 10).replace(/-/g, '');
  const randomPart = Math.random().toString(36).slice(2, 8).toLowerCase();
  return `model_${datePart}_${randomPart}`;
}

export function createEmptyModel(name = 'Новая модель') {
  const now = new Date().toISOString();
  const id = generateModelId();
  return {
    id,
    name,
    label: '',
    promptSnippet: '',
    heightCm: null,
    bodyType: '',
    faceExpressions: '',
    poses: '',
    background: '',
    previewSrc: '',
    dirPath: id, // Folder name matches ID
    imageFiles: [],
    createdAt: now,
    updatedAt: now
  };
}

export function validateModel(model, { requirePromptSnippet = false } = {}) {
  const errors = [];

  if (!model || typeof model !== 'object') {
    errors.push('Model must be an object');
    return { valid: false, errors };
  }

  if (!model.id || typeof model.id !== 'string') {
    errors.push('Model must have a string id');
  }

  if (!model.name || typeof model.name !== 'string' || model.name.trim() === '') {
    errors.push('Model must have a non-empty name');
  }

  // promptSnippet is optional during creation (generated by AI later)
  if (requirePromptSnippet && (!model.promptSnippet || typeof model.promptSnippet !== 'string')) {
    errors.push('Model should have a promptSnippet describing physical appearance');
  }

  // Validate heightCm if provided
  if (model.heightCm !== null && model.heightCm !== undefined) {
    if (typeof model.heightCm !== 'number' || model.heightCm < 100 || model.heightCm > 250) {
      errors.push('heightCm must be a number between 100 and 250');
    }
  }

  // Validate bodyType if provided
  if (model.bodyType && typeof model.bodyType !== 'string') {
    errors.push('bodyType must be a string');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Convert model data to a prompt snippet for image generation
 */
export function modelToPromptBlock(model) {
  if (!model) return '';

  const parts = [];

  if (model.promptSnippet) {
    parts.push(model.promptSnippet);
  }

  if (model.faceExpressions) {
    parts.push(`Expression: ${model.faceExpressions}`);
  }

  if (model.poses) {
    parts.push(`Pose style: ${model.poses}`);
  }

  if (model.background) {
    parts.push(`Model Background/Vibe: ${model.background}`);
  }

  return parts.join('\n');
}

